# Generated by Django 5.1.3 on 2024-11-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='monolit.post'),
        ),
    ]
